spring.application.name=payment-adapter
# Manual Switch: change this to a payment provider to activate it
payment.provider.active=PAYPAL
# PayPal Configuration
# Remember to set the client ID and secret from the .env file for local development and testing
paypal.sandbox.client-id=${PAYPAL_SANDBOX_CLIENT_ID}
paypal.sandbox.client-secret=${PAYPAL_SANDBOX_CLIENT_SECRET}
paypal.production=false

# Format: mongodb://[host]:[port]/[databaseName]
spring.data.mongodb.uri=mongodb://localhost:27017/payment_adapter_db