spring.application.name=payment-adapter
# Manual Switch: change this to a payment provider to activate it
payment.provider.active=PAYPAL
# PayPal Configuration
paypal.client.id=${PAYPAL_SANDBOX_CLIENT_ID}
paypal.client.secret=${PAYPAL_SANDBOX_CLIENT_SECRET}
paypal.production=false